plugins:
  - tableau_hll

settings:
  log-level: error
  intercept-log: logs/intercept.log
  general-log: logs/general.log

instances:
  - listen:
      name: proxy
      host: 127.0.0.1
      port: 5111
    redirect:
      name: postgresql
      host: 127.0.0.1
      port: 5432
    intercept:
      commands:
        queries:
          - plugin: tableau_hll
            function: rewrite_query
        connects:
      responses:
